### ISSUE TITLE
Consider renaming package to something more generic

### ISSUE THREAD

**Issue by prochnowc** [wintoncode/Winton.Extensions.Configuration.Consul#1]
Thanks for this good piece of code.

Please consider renaming the package to something more generic as this package is not dependent on AspNetCore.

Choc13.Extensions.Configuration.Consul would be more suitable i would say, what do you think?

**Comment by Choc13** [comment]
Hi @prochnowc,

Thanks for your interest in the project. 

If you look in the [project.json](https://github.com/Choc13/AspNetCore.Configuration.Consul/blob/master/src/AspNetCore.Configuration.Consul/project.json) then you will see the following 3 dependencies:

```
"Microsoft.Extensions.Configuration.Abstractions": "1.0.0",
"Microsoft.Extensions.Configuration.Json": "1.0.0",
"Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0"
```

These are all coming from the [AspNet Core Configuration project](https://github.com/aspnet/Configuration). So this is where the dependency on AspNetCore comes from. The library is directly extending the `IConfigurationProvider` and `IConfigurationSource` interfaces and so is tied to how configuration is loaded and provided for AspNet Core applications. 

I'd be interested to know how you were planning on using this project? What application framework did you want to use it with? Or have you already managed to integrate it with you project? Perhaps there is common functionality that can be abstracted out into a platform agnostic package here. However it is mostly just using [consuldotnet](https://github.com/PlayFab/consuldotnet) for communicating with Consul, so it might be better to implement your own for the framework you are interested in.

Thanks

**Comment by prochnowc** [comment]
@Choc13 I'm not really with you.

We're also building console applications using .NET core and Microsoft.Extensions libraries .. these console apps do not have any dependencies on Microsoft.AspNetCore libraries. Besised that, whilst Microsoft.Extensions.* library are contained in AspNetCore repository they have no dependency on AspNetCore. In fact if they were tied to AspNetCore, MS would have named them Microsoft.AspNetCore.Extensions.

Look for example at other projects.. e.g. Autofac. They named integration to Microsoft.Extensions.DependencyInjection also Autofac.Extensions.DependencyInjection and not Autofac.AspNetCore.DependencyInjection.

To be clear, your library works perfectly in .NET Core Console Apps which dont have any dependency on AspNetCore - and my issue with the name is only about "beautiness".

**Comment by Choc13** [comment]
Ah I see. the fact that those extensions were under the AspNet organisation in GitHub gave me the impression they only worked on AspNet. But yes there would be nothing inherent about it that would prevent it from working with a console application.

I will rename the package to something that is more aligned with how other third parties have named theirs.

**Comment by ah-** [comment]
Thanks for the good suggestion! Renamed it.
