### ISSUE TITLE
Slashes in JSON keys mess up configuration system

### ISSUE THREAD

**Issue by jmezach** [wintoncode/Winton.Extensions.Configuration.Consul#113]
Let me start by giving some context. I've been developing an API gateway using [Ocelot](https://github.com/ThreeMammals/Ocelot) which has a buit-in mechanism for reading its configuration from Consul. Since that project seems to be abandoned we are evaluating switching over to [YARP](https://github.com/microsoft/reverse-proxy) which doesn't have Consul configuration built-in. But it does read config from ASP.NET Core's configuration system out-of-the-box so I found this library which plugs into that so that we can switch over to YARP and keep our configuration in Consul as we have currently with Ocelot.

I did some testing of that setup yesterday and I ran into issue microsoft/reverse-proxy#410. My initial thought was that it was a YARP issue, but after trying the same setup using just appsettings.json I don't get the same issue which leads me to believe the issue might be in this library.

I've setup Consul configuration using this piece of code in my `Program.cs`:

```csharp
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
            .ConfigureAppConfiguration((context, builder) =>
            {
                // Only load Consul configuration for development
                if (!context.HostingEnvironment.IsDevelopment())
                {
                    // Add Consul configuration
                    builder.AddConsul("my/apigateway", options => { options.ReloadOnChange = true; });
                }
            });
```

Then in Consul I created the `my/apigateway` folders and in there I created a `ReverseProxy` folder in which I put a `Clusters` key with the following content:

```json
{
  "test": {
    "Destinations": {
      "test/destination1": {
        "Address": "https://localhost:5003/api/"
      }
    }
  }
}
```

This is consistent with the [documented configuration examples](https://microsoft.github.io/reverse-proxy/articles/configfiles.html) for YARP. However, this leads to an exception being thrown by YARP when using a route that uses the `test` cluster stating there are is no configuration for the destination. As soon as I remove the slash in `test/destination1` everything is working as expected.

I'm not here to shift blame to this library or anything, I guess I'm just wondering if there is a known issue with having a slash in the key which makes the configuration incompatible with this library.

**Comment by Choc13** [comment]
Hi @jmezach,

Thanks for raising this. I've not done a full investigation, but I suspect this is a bug in the way config is parsed. 

This line [`KvPairExtensions`](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/d1023c3fbc39e8331d2339e2b78084338af73908/src/Winton.Extensions.Configuration.Consul/Extensions/KVPairExtensions.cs#L26) seems likely to be causing the issue. I think the aim there is to deal with the fact that part of the key might be coming from the path to the key in consul (which will naturally contain `/`'s and so should be replaced with the config délimiter which is `:`. However, your case highlights that we should be more intelligent about which part of the key we apply that normalisation to.

I think it basically just needs to be done before we try and parse the value (e.g as JSON) but after we've stripped off any key prefix that needs to be removed.

Nonetheless it should be simple to write a failing test case for this and then fix it. I can probably look at this tomorrow (Monday UK time), but if you need it sooner then feel free to have a go yourself and open a PR.

**Comment by Choc13** [comment]
@jmezach I can't seem to reference you directly on the PR, but would like your feedback on whether I've addressed the issue correctly. 

The fix is [here](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/114/files#diff-ec6b0da314f7449611d4f209cc0c8946R25) and [this](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/114/files#diff-d08b1660480c0b3160678708f51da42bR140) is the main test case for it. The test case ensures that the way in which the consul key and the parsed value are combined produces the correct results, when the keys in the parsed value contain a forward slash. 

There is also [this](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/114/files#diff-5206eadb677aeca26aaec749009e3249R34) test case which makes sure that the JSON parser itself will deal with forward slashes in keys too, by making sure it does nothing special with them.

Let me know if you think this has solved it.

**Comment by jmezach** [comment]
@Choc13 Looking at the changes I think this will work for my scenario. Is there a prerelease version I could give a try just to be sure? I can test it fairly quickly ;).

**Comment by Choc13** [comment]
Annoyingly it looks like I've only configured the build to publish from `master` and `release` branches, so that build hasn't been published. 

I'll get it merged today given it's a simple change and all the tests are passing and then they'll be a pre-release you can try.

**Comment by Choc13** [comment]
@jmezach the pre-release [`3.1.0-rc0001`](https://www.nuget.org/packages/Winton.Extensions.Configuration.Consul/3.1.0-rc0001) is now published. Let me know once you've tested it out. If it's fine I'll release as `3.1.1`.

**Comment by jmezach** [comment]
@Choc13 I can confirm that it works as expected with 3.1.0-rc0001

**Comment by Choc13** [comment]
Great! [`3.1.1`](https://www.nuget.org/packages/Winton.Extensions.Configuration.Consul/3.1.1) has been published now 🚀
