### ISSUE TITLE
Old dependencies being flagged as vulnerabilities - new version?

### ISSUE THREAD

**Issue by GimmeDaKitty** [wintoncode/Winton.Extensions.Configuration.Consul#126]
Hi, 
first of all, thank you to all the contributors for this wonderful library.
Our vulnerability scans have flagged some vulnerabilities that can be traced to this package. 
Is it planned to release a new version of this library? Otherwise we'll have to find alternatives.

**Comment by GimmeDaKitty** [comment]
@Choc13 thanks for the quick reply :)
It's about consul 0.7.2.6 and its dependency on System.Net.Http 4.3.0 and WinHttpHandler.

The below is an extract of our dependency graph: 
```
"Consul/0.7.2.6": {
        "type": "package",
        "dependencies": {
          "NETStandard.Library": "1.6.1",
          "Newtonsoft.Json": "10.0.2",
          "System.Collections": "4.3.0",
          "System.Linq": "4.3.0",
          "System.Net.Http": "4.3.0",
          "System.Net.Http.WinHttpHandler": "4.0.0",
          "System.Runtime": "4.3.0",
          "System.Security.Cryptography.X509Certificates": "4.3.0",
          "System.Text.RegularExpressions": "4.3.0",
          "System.Threading": "4.3.0",
          "System.Threading.Thread": "4.0.0"
        },
        "compile": {
          "lib/netstandard1.3/Consul.dll": {}
        },
        "runtime": {
          "lib/netstandard1.3/Consul.dll": {}
        }
```

**Comment by Choc13** [comment]
Ah right OK. That is the one package I was hoping you weren't going to mention, but I guess it was always going to be the most likely culprit. There's been another issue open for a while #85 in which I wanted to remove/change this dep, but I never got around to doing the work. 

I think that the consul dotnet lib was taken over by a different maintainer (it's [here](https://github.com/G-Research/consuldotnet) now I think). I think the best course of action would be to try updating to that new version. 

I am also hopeful that this new version has removed all of the old NET Framework dependencies as that would clean up some of the conditional compilation we have in here to deal with both dotnet core and NET Framework.

Sorry this might end being a larger change, but it is something that would be an excellent improvement.

**Comment by GimmeDaKitty** [comment]
Thanks for the clarification, I appreciate it. Not sure what we will do in the meantime; I'll have a look at the source code and see whether I can contribute something.

**Comment by GimmeDaKitty** [comment]
So far updaetd the dependency, and removed the NET framework target and the conditional compilation (if this is just to remove 461 from the .csproj like so (bold part removed): 
<TargetFrameworks>netstandard2.0;**net461**</TargetFrameworks>

Tests pass, no compilation warnings or errors on the IDE, and 'Website' project runs. However, I must be missing something because Website461 project does not start up.

Both Net461Website and Website projects reference project:     

`<ProjectReference Include="..\..\src\Winton.Extensions.Configuration.Consul\Winton.Extensions.Configuration.Consul.csproj" />`

Yet for Net461Website I get this error:
```
Method not found: 'Void Consul.ConsulClient..ctor(System.Action`1<Consul.ConsulClientConfiguration>, System.Action`1<System.Net.Http.HttpClient>, System.Action`1<System.Net.Http.HttpClientHandler>)'.
   at Winton.Extensions.Configuration.Consul.ConsulClientFactory.Create()
```

I was looking for build tasks in the project but I can't find anything. 
The Net461 folder that is created after the build contains the consul.dll. The dll *is there. You have any clue?

**Comment by Choc13** [comment]
Ah yes that does ring a bell. I believe I fixed this exact problem before in [#44](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/44). 

That was the conditional compilation part that I was referring to before, where I referenced some other system libs for net461. It appears though that is now not present in the version on master so I'll see if I can figure out why/when it was removed. 

Would you mind checking whether the net461 website project runs from the master branch too. 

It might just be that we have to drop support for net461. I'll have a closer look tomorrow though.

**Comment by GimmeDaKitty** [comment]
net461Website in master won't work and throws the same exception 
```
'Method not found: 'Void Consul.ConsulClient..ctor(System.Action`1<Consul.ConsulClientConfiguration>, System.Action`1<System.Net.Http.HttpClient>, System.Action`1<System.Net.Http.HttpClientHandler>)'.
   at Winton.Extensions.Configuration.Consul.ConsulClientFactory.Create()'
```

I did see references to a build.sh script indeed but was nowhere to be found in the repository. Seeing #44  explains it.

I created this PR for reference in the discussions
https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/127

**Comment by Choc13** [comment]
OK, thanks for checking master. I just did some digging and it looks like the conditional compilation for `net461` was erroneously removed in [this commit](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/commit/9e24a715e4fce1279a4822217908afc0f9e6dcaf#diff-af73d90db700f6428f29c6202de2cc0bc74e890ee069f1a2f7f27c11648936ebL20). 

I think I should have just removed `Newtonsoft.Json` from that section rather than deleting the whole block. Let's try adding `net461` back to the target frameworks list and adding that conditional compilation block back, minus the `Newtonsoft.Json` dep. Then we can retest and you can see whether or not your vulnerability scanner still reports an issue or not too.

I'll comment on the PR to make it clearer.

**Comment by GimmeDaKitty** [comment]
The new version with the change did remove the vulnerable dependency.
Thanks again for the support, closing issue
