### ISSUE TITLE
Values are not reloaded when a key is deleted

### ISSUE THREAD

**Issue by andrewvk** [wintoncode/Winton.Extensions.Configuration.Consul#128]
If the configuration key is deleted in Consul or even set to an empty string, the configuration is not reloaded, it still has the old value.
This behavior is explicitly specified in the code, and I can't figure out the reason for it.

**Comment by andrewvk** [comment]
https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/d9705de56f83572fc96d5e880ae24301da92cb18/src/Winton.Extensions.Configuration.Consul/ConsulConfigurationProvider.cs#L137
result.HasValue returns false if the key is deleted or contains an empty string.

**Comment by andrewvk** [comment]
I think the best approach is to do it completely similar to standard providers, such as FileConfigurationProvider.
The code is like this:
```
private void Load(bool reload)
{
    IFileInfo file = Source.FileProvider?.GetFileInfo(Source.Path);
    if (file == null || !file.Exists)
    {
        if (Source.Optional || reload) // Always optional on reload
        {
            Data = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        }
        else
        {
            var error = new StringBuilder(SR.Format(SR.Error_FileNotFound, Source.Path));
            if (!string.IsNullOrEmpty(file?.PhysicalPath))
            {
                error.Append(SR.Format(SR.Error_ExpectedPhysicalPath, file.PhysicalPath));
            }
            HandleException(ExceptionDispatchInfo.Capture(new FileNotFoundException(error.ToString())));
        }
    }
```
That is, when reload, the behavior is always the same as the optional source, no matter what the original settings are.

**Comment by andrewvk** [comment]
Made PR - https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/129

**Comment by Kaston** [comment]
Hi @andrewvk, we've faced this issue in our project. Is there an expected release date for this fix?

**Comment by andrewvk** [comment]
> Hi @andrewvk, we've faced this issue in our project. Is there an expected release date for this fix?

Hi.
The question is to the wrong person. You should ask the owners of the project.

**Comment by Choc13** [comment]
Hey, sorry for not getting this released sooner. Let me try and get a new version out this weekend.

**Comment by Choc13** [comment]
🚀 [3.3.0](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/releases/tag/3.3.0) has been released and is available via [NuGet](https://www.nuget.org/packages/Winton.Extensions.Configuration.Consul/3.3.0) 📦
