### ISSUE TITLE
.NET 7.0 and new way read Configuration

### ISSUE THREAD

**Issue by toper** [wintoncode/Winton.Extensions.Configuration.Consul#131]
Do you have plan, upgrade library to .NET 7 ?
Actualy it throw excetpion: 
_"Cannot access a disposed object. Object name: 'ConfigurationManager'."_

My mistake, documentation need correct ;)

**Comment by Choc13** [comment]
Ok, just checking this is all good then now? Was this a problem with our docs or the Microsoft Configuration documentation?
