### ISSUE TITLE
Support Writing to consul 

### ISSUE THREAD

**Issue by mazaheriMahdi** [wintoncode/Winton.Extensions.Configuration.Consul#138]
i have a configuration template that i like to write to consul on service startup so i need to write new keys back to consul but currently writing in consul through this library is not supported.

**Comment by Choc13** [comment]
This library only supports fetching config from Consul and loading that into the dotnet configuration format. 

If you need to write to Consul then I would suggest using the dotnet consul library directly and writing the code to insert whatever you need. You could invoke that as part of app startup if you need to, but it's out of the scope of this library unfortunately.
