### ISSUE TITLE
Bug in JsonConfigurationParser regarding type conversion

### ISSUE THREAD

**Issue by mindcrash** [wintoncode/Winton.Extensions.Configuration.Consul#47]
While parsing Json data we noticed that the PrimitiveVisitor does not respect the default value of JsonTextReader's CultureInfo (which, by the way, is CultureInfo.InvariantCulture by default).

This causes issues when trying to read invariant double values from json data and try to convert them to actual invariant double values within code (e.g. the value 0.1).

We traced this issue to [line 36 of JsonPrimitiveVisitor.cs](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/blob/master/src/Winton.Extensions.Configuration.Consul/Parsers/Json/JsonPrimitiveVisitor.cs#L36):

```csharp
new KeyValuePair<string, string>(key, primitive.ToString())
```

will cause the token to be converted to its stringified counter type ignoring the culture set in the parser (e.g. "0.1" in JSON becomes "0,1" in the configuration data)

This can be easily solved by using the following method provided by Newtonsoft Json instead:

```csharp
new KeyValuePair<string, string>(key, primitive.Value<string>())
```

This will convert the token to a stringified counter type respecting the set culture (e.g. "0.1" in JSON remains "0.1" in code).

I'm in crunch mode at the moment but I can supply a PR later on if you want (or you can simply apply the fix and write a small test to confirm the fix yourself).

**Comment by Choc13** [comment]
Hi @mindcrash and thanks for reporting that. 

I'll take a quick look now. As you say it doesn't sound like it should be too hard to write a failing test and then fix. Out of interest which version of the library are you using? Although, I'm pretty sure this will be present in all versions anyway.

**Comment by Choc13** [comment]
Versions 1.0.2 and 2.0.2 will be available via NuGet shortly and include the fix for this issue.
