### ISSUE TITLE
Configuration hierarchy reading

### ISSUE THREAD

**Issue by zorannik** [wintoncode/Winton.Extensions.Configuration.Consul#59]
Hi,

It seems there is an issue with reading configuration hierarchy in package version 2.1.1. Whenever there is an overlap in names of rootKey and actual key in configuration the hierarchy will be ommitted. For example:
* AppName: ServiceBus
* RootKey: ServiceBus/Development/appsettings.json (the one passed to builder                     .AddConsul("ServiceBusUtilApi/Development/settings/"),
* ConsulKey: ServiceBus/Development/appsettings.json/Bus
* KeyValue: QueueName: "xxx"
* ExpectedResult: Bus:QueueName=xxx
* ActualResult: QueueName=xxx

## Steps to reproduce:
1) Go to consul and add the configuration from above
```bash
curl -X PUT localhost:8500/v1/kv/ServiceBus/
curl -X PUT localhost:8500/v1/kv/ServiceBus/Development/
curl -X PUT localhost:8500/v1/kv/ServiceBus/Development/appsettings.json/
curl -X PUT localhost:8500/v1/kv/ServiceBus/Development/appsettings.json/Bus/
curl -X PUT -d @- localhost:8500/v1/kv/ServiceBus/Development/appsettings.json/Bus/QueueName <<< xxx
```
2) Create new project and add nuget Winton.Extensions.Configuration.Consul
3) Add consul
```CSharp
builder
    .AddConsul(
        "ServiceBus/Development/appsettings.json",
        cancellationToken,
        options =>
        {
            options.Parser = new SimpleConfigurationParser();
        });
```
4) Try to read expected config value
```CSharp
public Startup(IConfiguration config)
            : base(config, Constants.ApiTitle)
        {
            var value = config["Bus:QueueName"];
        }
```
5) They key wont be found
5a) Alternatively you can you the sample app I attached to this issue [ConsoleApp1.zip](https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/files/2575676/ConsoleApp1.zip)

## Cause of the problem
The culprit for this lays in KVPairExtensions.cs line 26, specifically 
```CSharp
kvPair.Key.TrimStart(rootKey.ToCharArray())
```
namely for example above this line will return an empty string, due to the way TrimStart works with char array. To verify this you can run the code below in console
```CSharp
internal class Program
    {
        private static void Main(string[] args)
        {
            TrimMe("ServiceBus/Development/appsettings.json", "ServiceBus/Development/appsettings.json/Bus");
            TrimMe("ServiceBus/Development/appsettings.json", "ServiceBus/Development/appsettings.json/BusUtil");
            TrimMe("ServiceBus/Development/appsettings.json", "ServiceBus/Development/appsettings.json/Service");
            TrimMe("ServiceBus/Development/appsettings.json", "ServiceBus/Development/appsettings.json/ServiceConfig");

            Console.ReadLine();
        }

        private static void TrimMe(string root, string key)
        {
            var trimResult = key.TrimStart(root.ToCharArray());
            Console.WriteLine($"Trim '{root}' from '{key}'");
            Console.WriteLine($"Trim result: '{trimResult}'");
        }
    }
```

## Solution
To address this, I quickly whipped up a piece of code that does exact "TrimStart", and replaced TrimStart call. There are many other ways of achieving this, this was just quickest for me.
```CSharp
internal static string GetKey(this KVPair kvPair, string rootKey, string pairKey)
        {
            string key = string.Empty;
            string consulKey = kvPair.Key;
            if (consulKey.StartsWith(rootKey))
            {
                key = consulKey.Remove(0, rootKey.Length);
            }

            key = key.TrimStart('/').TrimEnd('/');
            return $"{key}:{pairKey}"
                .Replace('/', ':')
                .Trim(':');
        }
```
## Approach
I have already fixed this locally and added some unit tests, so I can also do a pull request if you like? 
If you need more information feel free to contact me.

**Comment by Choc13** [comment]
@zorannik thanks for reporting this. Yes, this is obviously a bug. By verifying this locally, I've already made the fix myself, so I shall submit a PR now and got this released as a patch ASAP.

**Comment by zorannik** [comment]
Thanks

**Comment by Choc13** [comment]
Feel free to review the PR too. I couldn't add you as a formal reviewer because you're not in the wintoncode org, but let me know if you see any other issues with that fix, or would like me to add any more test cases.

**Comment by zorannik** [comment]
Thanks for the quick fix, it looks fine :) 
Personally I would prefer a separate method to handle key composition completely, but that is just me :)

**Comment by Choc13** [comment]
2.1.2 is published on [NuGet](https://www.nuget.org/packages/Winton.Extensions.Configuration.Consul/2.1.2) but might take a while to be indexed.
