### ISSUE TITLE
[QUESTION] Configuration not picking up changes when adding a new key

### ISSUE THREAD

**Issue by bdelsaz** [wintoncode/Winton.Extensions.Configuration.Consul#79]
We are using consul configuration on services on a kubernetes cluster. We have noticed that when we add a new key-value, the consul configuration extension does not pick up the changes. The configuration remains unaware of the new key. 

This is how we use the consul configuration extension:

```
public static IWebHostBuilder CreateWebHostBuilder(string[] args, CancellationTokenSource cancellationTokenSource) =>
            Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .ConfigureAppConfiguration((builderContext, config) =>
                {
                    var env = builderContext.HostingEnvironment;

                    config
                        .AddJsonFile("appsettings.json", false, true)
                        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", true, true)
                        .AddEnvironmentVariables();

                    var consulConfig = config.Build().GetSection("consulConfig").Get<ConsulConfig>();

                    if (consulConfig.Enabled)
                    {
                        config.AddConsul($"{env.EnvironmentName}/demo", cancellationTokenSource.Token,
                            o =>
                            {
                                o.ConsulConfigurationOptions = a => { a.Address = new Uri(consulConfig.Address); };
                                o.Optional = env.IsDevelopment();
                                o.ReloadOnChange = true;
                            });
                    }
                })
                .UseStartup<Startup>();
    }
```

Then we inject the configuration using ```IOptionsMonitor<>``` and DI.
Is this by design? Any pointers on how we could solve this without having to restart our pods so that they pick up the new values?

**Comment by Choc13** [comment]
Hi @bdelsaz,

It sounds like what you want to achieve is possible and the setup you have shown and described sounds correct. Let's see if we can figure out what's going on? 

Firstly, is the key that you're adding under the root key that you're loading from Consul?

**Comment by bdelsaz** [comment]
@Choc13 thanks for your answer. I am adding keypath "AR" with all the subfolders (in red), where Production/demo is the root key, which I set in AddConsul above.

![image](https://user-images.githubusercontent.com/46991222/66485486-31f4a500-eaa9-11e9-838c-fded378ca597.png)

I have tried to add the keys:
- From the consul/ui endpoint
- Using consul's REST API

Could it be that I add my configuration like this on the ConfigureServices? 
```
services.Configure<ServiceConfiguration>(Configuration.GetSection("demoConfig"));
```
So, demoConfig differs from base key 'Production' (?)

**Comment by Choc13** [comment]
Your set up looks correct wrt the section you are binding to `ServiceConfiguration` and I'm assuming that the initial config is coming through at startup so that would be further proof you have this correct. 

Could you tell me whether it detects changes to the values of existing keys? For example, if you modify `demoConfig->YPE->TM->key1`?

**Comment by bdelsaz** [comment]
Yes, if I change the key it will pick up the changes.

**Comment by Choc13** [comment]
OK that's interesting, let's see if we can reproduce the issue. This repo contains a sample project so we can see if we can simulate it with that, it runs Consul in a docker container so is quite easy to get going with. 
I might not get time for a little while (couple of days), but if you're able to repro the issue then please go ahead and let me know what you find.

**Comment by bdelsaz** [comment]
I assume you refer to the project under test\Website. I'll have a look at this project.

**Comment by Choc13** [comment]
That's the one.

**Comment by bdelsaz** [comment]
Test project was not working for me; swagger was not displaying on home URI. 
I have created a PR suggsesting some changes
https://github.com/wintoncode/Winton.Extensions.Configuration.Consul/pull/80

**Comment by bdelsaz** [comment]
Yes. Now I'm setting up a test with changing configuration to reproduce my problem.
This is my first merged PR in an open source project wohoo! 🎉

**Comment by bdelsaz** [comment]
The test project picks up the changes as expected. After carefully retesting against local consul docker container, it seems the problem was on my test setup😅
Thank you for the support, I am glad this exercise has helped me know Consul clients and your extension better.
For completeness I have updated my PR changing the launchsettings of the Website project, 'swagger' initial path on IIS profile was no longer needed.

**Comment by Choc13** [comment]
😌 Phew! Glad you figured it out 👍
