### ISSUE TITLE
Update dependencies for .NET Core 3.1 LTS

### ISSUE THREAD

**Issue by gitfool** [wintoncode/Winton.Extensions.Configuration.Consul#89]
https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.0/3.1.0.md

**Comment by Choc13** [comment]
Are you just referring to the deps in the test projects etc? In general I try and keep this lib on the lowest possible TFM and version of it's deps for a given major version to increase compatibility with applications.

**Comment by gitfool** [comment]
@Choc13 No,` Microsoft.Extensions.*` bumps to `3.1.0`. IIRC you were keeping those in line with latest.

**Comment by Choc13** [comment]
Ah, my intention is to keep them inline with the latest majors. If applications upgrade their `Microsoft.Extensions.*` deps then they will pick up latest and this lib should still be compatible as it works against 3.0. But in general we want applications to chose when they adopt the latest version of those things, which they will do when they upgrade to ASP.NET Core 3.1. I would only perform minor updates of the `Microsoft.Extensions.*` deps here if they contained a new feature that we required to improve our lib.
